services:
  init:
    image: ghcr.io/nordic-escape/team-battle:latest
    platform: linux/arm64
    user: "0"
    command: sh -c "cp -r /app/dmx/* /dmx-out/"
    volumes:
      - /home/nordic-escape/dmx:/dmx-out

  app:
    image: ghcr.io/nordic-escape/team-battle:latest
    platform: linux/arm64
    depends_on:
      - init
    environment:
      DATABASE_URL: "file:/app/production.db"
      QLC_HOST: "host.docker.internal:9999"
    ports:
      - "3000:3000"
    volumes:
      - /home/nordic-escape/production.db:/app/production.db
      - /home/nordic-escape/dmx:/app/dmx
    extra_hosts:
      - "host.docker.internal:host-gateway"